### ISSUE TITLE
Differences between plotter.plot() and plotter.as_one_image()

### ISSUE THREAD

**Issue by Brieden** [MatthewDaws/TileMapBase#18]
Thank you for the project <3
I get different shapes for plotter.plot() and plotter.as_one_image(), but I expected the same image and shape. It seems to me that as_one_image() is not xlim and ylim correctly. I look forward to your feedback, whether I have understood correctly.

```Python
import matplotlib.pyplot as plt
import tilemapbase
tilemapbase.start_logging()
tilemapbase.init(create=True)
tt_OSM = tilemapbase.tiles.build_OSM()

N, E, S, W = 47.36672642143951, 8.546733172519925, 47.36583977605192, 8.54539077196696
extent = tilemapbase.Extent.from_lonlat(
                longitude_min = W, 
                longitude_max = E,
                latitude_min = S, 
                latitude_max = N)

fig, ax = plt.subplots(); ax.xaxis.set_visible(False), ax.yaxis.set_visible(False)
tilemapbase.Plotter(extent, tt_OSM, width=600).plot(ax)
plt.show()

mapbase = tilemapbase.Plotter(extent, tt_OSM, width=300)
image = mapbase.as_one_image()
print(image.size)
plt.imshow(image)
plt.plot()
```

Should be a square like this: plotter.plot()
![plotter_plot](https://user-images.githubusercontent.com/13276236/89640193-57ac2f80-d8af-11ea-871e-9ade99af3107.png)

But as_one_image is to wide:
![plotter_as_one_image](https://user-images.githubusercontent.com/13276236/89640191-57139900-d8af-11ea-9ae2-48d2441975fe.png)

**Comment by MatthewDaws** [comment]
Sorry it has taken me so long to get to this.  It's been so long since I wrote the code!

The `as_one_image` output, in your example, is also slightly taller (if you look closely you can see slightly more of tile above and below).

Ah, right.  If you look at the code for a while, you realise that `as_one_image` produces an image which is always a whole number of tiles width and height.  In this case, we have

    > tt_OSM.tilesize
    256

And indeed the `as_one_image` output is 3 tiles wide and 2 tiles high.

Your example is unfortunate, in that the extent is _almost exactly_ 2 tiles high, and aligned to tile boundaries.  A more "generic" example would make it clearer that `as_one_image` is always oversized, and then clipped to the axes to give, exactly, the requested `extent`.

I think I made this decision to push all the clipping work into `matplotlib` in the belief that it would be higher quality, rather than trying to write my own code to clip (which would probably lead to small missing pixels in the matplotlib output.

**Comment by MatthewDaws** [comment]
Have tidied up some of the doc strings, and in particular now make clear what `as_one_image` does.
